### ISSUE TITLE
Unable to get any results from chat in standard Docker-compose via README

### ISSUE THREAD

**Issue by Handfish** [BenderV/ada#1]
Hi, 

I created an OpenAI API key and spun up the docker compose. The chat instantly clears upon send, and neither the browser console or the docker consoles log any information about the failed request. Any ideas?

**Comment by Handfish** [comment]
I commented out the view in the docker-compose, and am running via `yarn dev` and it is successfully providing error messages from OpenAI now.

**Comment by nhut-ntm** [comment]
Hi there, I am trying to run the project locally on my laptop. I first clone the project to local directory, everything is kept orginally, and I runthe command docker-compose up -d in the powershell terminal in VSCode, then I run into several problems. I just want to ask that am I doing right or I need to do anything else. Forgive me for asking some silly questions as I have no previous experience with Docker or Flask. Thank you very much.

**Comment by nhut-ntm** [comment]
Hi there, I ran into the same problem as you and I also commented out the view section in the docker-compose file and run the front end via yarn dev but when I open localhost:5173, there is nothing where I can enter prompts shown. Did you encounter the same thing or is there anything way to fix the problem. Many thanks.

**Comment by BenderV** [comment]
@Handfish @nhut-ntm thanks for the issue ! I forgot to add the nginx socket.io route. This should be [fixed with the last commit](https://github.com/BenderV/ada/commit/1bc2a581df3868bfdfd88c587f74164aed5ae5fc).
